apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-n0ay
  namespace: samburrai-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:caafcde130d0940ff534fe589b40865109f94ee2660bcdfd9f05ba9671357093
        name: my-java-quarkus
        resources: {}
status: {}
